trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: |
    echo "Repository contents"
    pwd
    ls -la
  displayName: "Show Files"

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)'
    artifact: 'website'
    publishLocation: 'pipeline'