trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: "Test Azure Connection"

  inputs:
    azureSubscription: 'azure-lab-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Connected to Azure"

      az account show --output table

      echo "Resource Groups:"
      az group list --output table